apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: ${PROMETHEUS_SERVICE_URL}
    isDefault: true
    jsonData:
      timeInterval: "30s"
      httpMethod: "POST"
      queryTimeout: "60s"
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: "tempo"
    secureJsonData:
      basicAuthPassword: ${PROMETHEUS_PASSWORD} # If using auth
